apiVersion: v1
kind: Service
metadata:
  name: {{ include "connect4-chart.fullname" . }}
  labels:
    app: {{ include "connect4-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "connect4-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
