name: Deploy to Dev (Minikube)

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t connect4-web .

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # This assumes your K8s cluster is accessible (e.g., via Kubeconfig Secret)
      - name: Set up Kubeconfig
        run: |
          echo "$KUBECONFIG_DATA" | base64 --decode > $HOME/.kube/config
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}

      - name: Deploy to Dev with Helm
        run: |
          helm upgrade --install connect4-dev ./connect4-chart \
            -f ./connect4-chart/values-dev.yaml \
            --namespace dev --create-namespace
